Train rust dataset
SecurityLab-UCD/UniTSyncer pull request #20
Opened 2023-11-22 00:07 UTC by HockJC

2023-11-22 02:19 UTC, EYH0602 requested changes

2023-11-22 02:19 UTC, EYH0602 commented on .DS_Store
please remove `.DS_Store`

2023-11-22 02:19 UTC, EYH0602 commented on marshallpierce/rust-base64
why is this submodule needed?

2023-11-22 02:19 UTC, EYH0602 commented on training/.DS_Store
please remove

2023-11-22 02:19 UTC, EYH0602 commented on training/data/Alexhuszagh-minimal-lexical.success.jsonl_0.txt
these data is reproducable using dataloader, please store them in memory and don't commit them. please remove

2023-11-22 02:26 UTC, HockJC commented on training/data/Alexhuszagh-minimal-lexical.success.jsonl_0.txt
ok.

> these data is reproducable using dataloader, please store them in memory and don't commit them. please remove

2023-12-04 22:22 UTC, DataCorrupted requested changes

2023-12-04 22:22 UTC, DataCorrupted commented on results/checkpoint-1000/README.md
DO NOT put results in git. This is a dirty branch now, please find the commit that introduced these files and send a new PR (or force push to this branch).

If it is something you want to note down, write it in confluence with a link to our server address.

2023-12-04 22:22 UTC, DataCorrupted commented on training/data/test_dataset.jsonl
I don't encourage you to put the training data in the repo as well.

2023-12-04 22:28 UTC, HockJC commented on results/checkpoint-1000/README.md
OK

2024-01-12 22:49 UTC, EYH0602 commented
@HockJC please open  PR at https://github.com/SecurityLab-UCD/FuzzAugmentation for the updates.

2024-01-12 22:49 UTC, closed without merging